// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNcUxAgnYc_aXNa3UBNYJ6R-NlefIJirU',
    appId: '1:386123382707:web:8b1e883c1ace79e830d5c6',
    messagingSenderId: '386123382707',
    projectId: 'tasks-collector-66a94',
    authDomain: 'tasks-collector-66a94.firebaseapp.com',
    storageBucket: 'tasks-collector-66a94.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB23-ReNkylp3JaoWF0e2_sdK5hA9Eylk4',
    appId: '1:386123382707:android:f10c1cfed8f7bb7630d5c6',
    messagingSenderId: '386123382707',
    projectId: 'tasks-collector-66a94',
    storageBucket: 'tasks-collector-66a94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC07_uvsjLNE2B4eCphj3IQKyXg1tihwEU',
    appId: '1:386123382707:ios:98ac877a7fac2af030d5c6',
    messagingSenderId: '386123382707',
    projectId: 'tasks-collector-66a94',
    storageBucket: 'tasks-collector-66a94.firebasestorage.app',
    iosBundleId: 'com.alwasl.taskscollector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC07_uvsjLNE2B4eCphj3IQKyXg1tihwEU',
    appId: '1:386123382707:ios:0f7eaf7b68960ada30d5c6',
    messagingSenderId: '386123382707',
    projectId: 'tasks-collector-66a94',
    storageBucket: 'tasks-collector-66a94.firebasestorage.app',
    iosBundleId: 'com.example.tasksCollector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNcUxAgnYc_aXNa3UBNYJ6R-NlefIJirU',
    appId: '1:386123382707:web:6c04fcb7a9bfc7b730d5c6',
    messagingSenderId: '386123382707',
    projectId: 'tasks-collector-66a94',
    authDomain: 'tasks-collector-66a94.firebaseapp.com',
    storageBucket: 'tasks-collector-66a94.firebasestorage.app',
  );
}
